from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional, Union

class HistoricalLaborDisplacementStudy(BaseModel):
    """
    Schema for extracting data on historical labor displacement due to technology.
    """
    # Study Metadata
    authors: Optional[List[str]] = Field(['Audrey Freedman', 'J. Stephen Keyes (assistance)', 'Mable Elliott (assistance)'], description="List of authors' names.") # [cite: 38]
    title: Optional[str] = Field('IMPACT OF OFFICE AUTOMATION IN THE INSURANCE INDUSTRY', description="Full title of the study.") # [cite: 1, 26]
    year_of_publication: Optional[int] = Field(1966, description="The year the study was published.") # Inferred from GPO date [cite: 754] and surrounding pubs [cite: 2, 3]
    journal_or_publisher: Optional[str] = Field('U.S. Department of Labor, Bureau of Labor Statistics (Bulletin No. 1468)', description="Name of the journal or publication outlet (e.g., journal name, 'Working Paper', publisher).") # [cite: 1, 26]

    # Inclusion
    include_in_extraction: bool = Field(True, description="Should this study be included in the extraction based on relevance? (True/False)") # Meets criteria: empirical, pre-1980 tech (computers from 1954), labor impact.

    # Study Relevance (Only fill if include_in_extraction is True)
    topic: Optional[str] = Field('Impact of electronic computers (Electronic Data Processing - EDP) on employment trends and occupational structure in the U.S. insurance industry.', description="Brief description of the study's main topic related to technology and labor.") # [cite: 33, 34, 77]
    relevance_assessment: Optional[str] = Field('Included because it empirically examines the labor market impact (employment levels, occupational shifts) of a specific pre-1980 technology (electronic computers/EDP, introduced from 1954) within the US insurance sector, using survey and interview data.', description="Brief justification for inclusion/exclusion based on the review's scope (historical, pre-1980 tech, empirical labor impact).") # [cite: 33, 34, 35, 50, 436]
    technologies: Optional[List[str]] = Field(['Electronic computers', 'Electronic Data Processing (EDP)', 'Optical scanners', 'Magnetic ink encoding equipment', 'Mark sensing equipment', 'Data transmission systems'], description="Specific technologies or technological changes examined.") # [cite: 33, 78, 107, 110, 253, 262, 268, 278]

    # Study Design Characteristics (Only fill if include_in_extraction is True)
    study_type: Optional[str] = Field('Mixed-Methods', description="Type of study (e.g., Quantitative, Qualitative, Mixed-Methods).") # Primarily quantitative (surveys, tables) with qualitative elements (interviews, narrative) [cite: 35, 84, 91, 42, 43]
    methodology: Optional[str] = Field('Two-stage mail survey of insurance carriers, interviews with industry authorities and company executives, analysis of published reports.', description="Description of the research method used (e.g., historical analysis, econometric modeling, case study).") # [cite: 35, 84, 85, 88, 91, 92]
    occupations: Optional[List[str]] = Field(['Office employees', 'Tabulating-machine operators', 'General clerical workers', 'Keypunch operators', 'Calculating-machine operators', 'Supervisors (clerical)', 'EDP personnel (Systems analysts, programers, computer operators, peripheral equipment operators, input personnel, supporting clerical, supervisors, maintenance engineers)'], description="Specific occupation(s) studied.") # [cite: 58, 115, 117, 134, 136, 138, 322, 336, 344, 349, 355, 436]
    occupation_types: Optional[str] = Field('Main office occupations', description="Type of occupation (e.g., Main, Supplementary, Seasonal).") # [cite: 58, 83]
    occupation_classifications: Optional[List[str]] = Field('Omitted in source', description="Occupational classification codes used, if any (e.g., HISCO, ISCO, PSTI).") # Specific codes not mentioned.
    gross_vs_net: Optional[str] = Field('Both', description="Focus of displacement measurement (Gross, Net, Both).") # Discusses net employment slowdown and gross occupational shifts[cite: 123, 402, 436].
    sample_size: Optional[Union[int, str]] = Field('410 companies (Stage 1 survey, 89% industry empl.); 246 companies (Stage 2 survey response); ~15,000 EDP employees studied in detail.', description="Number of workers/entities studied, or description if number not available.") # [cite: 86, 114, 167, 321]
    sample_characteristics: Optional[str] = Field('US Insurance Carriers (Life, Property, Health); varied company sizes; home and field offices; office employees ~70-75% of total; nearly half women.', description="Demographic or other characteristics of the sample (e.g., age, gender, location, industry).") # [cite: 35, 53-59, 85, 160, 161]
    time_period_covered: Optional[str] = Field('1954-1963 (primary analysis), with outlook to 1975', description="The historical timeframe covered by the study (e.g., '1880-1900', '19th Century').") # [cite: 34, 170, 401, 499]
    time_period_start: Optional[int] = Field(1954, description="Start year of the period covered.") # [cite: 34, 50]
    time_period_end: Optional[int] = Field(1963, description="End year of the period covered.") # Main analysis end year [cite: 34, 170]
    geographical_focus: Optional[str] = Field('United States', description="Region, country, or specific location of the study.") # [cite: 1, 52]

    # Key Variables of Interest (Only fill if include_in_extraction is True)
    independent_variables_technologies: Optional[str] = Field('Adoption/presence of EDP systems, years of EDP experience, extent of EDP application implementation, use of optical scanners, use of data transmission systems.', description="Description of the independent variable(s) representing technology.") # [cite: 34, 154, 203, 255, 278, 399, 473]
    displaced_description: Optional[str] = Field('Focus on slowed hiring/employment growth and occupational shifts rather than direct layoffs. High attrition (esp. female clerical) and transfers/retraining absorbed most impacts. Specific occupations (tabulating, routine clerical, calculating) saw decreased employment. "Few individuals...were laid off as a direct result..."[cite: 444]. Adjustment mainly via attrition and transfer[cite: 445]. Limited specialist clerks disappeared[cite: 305].', description="Qualitative description of worker displacement.") # [cite: 123, 134, 136, 138, 143, 304, 305, 405, 436, 441, 444, 445]
    displaced_number: Optional[Union[float, str]] = Field('Not specified as layoffs; focus on occupational decline. E.g., ~70% of firms reported EDP caused decrease in tabulating-machine operator jobs[cite: 439]. 26% expected decline in general clerical by 1966[cite: 128].', description="Number or share (%) of workers displaced.") # [cite: 128, 135, 137, 138, 439]
    unemployment_underemployment_description: Optional[str] = Field('Not directly measured. Focus on slower overall employment growth and reduced entry-level opportunities, particularly for young women high school graduates.', description="Qualitative description of unemployment or underemployment following displacement.") # [cite: 139, 140, 507, 508, 509]
    unemployment_underemployment_number: Optional[Union[float, str]] = Field('Omitted in source', description="Number or share (%) of workers unemployed/underemployed or exiting the labor market after displacement.")
    duration_of_unemployment: Optional[str] = Field('Omitted in source', description="Reported duration of unemployment or underemployment after displacement.")
    wage_changes_description: Optional[str] = Field('Omitted in source', description="Description of wage changes for displaced workers upon re-employment.")
    wage_changes_percent: Optional[Union[float, str]] = Field('Omitted in source', description="Percentage change in wages for displaced workers (e.g., -10% or +5%).")

    # Quantitative Data (Fill if applicable and include_in_extraction is True)
    moderators: Optional[List[str]] = Field(['Company size', 'Type of insurance (Life, Property, Health)', 'Years of EDP experience', 'Use of optical scanners', 'Use of data transmission systems'], description="Factors influencing the technology-employment relationship (e.g., education, industry, union presence).") # [cite: 160, 171, 179, 215, 318, 399, 405, 473, 474]
    effect_sizes: Optional[str] = Field('Omitted in source (Standard effect sizes not reported; findings presented as percentages/growth rates).', description="Reported effect sizes (e.g., 'Pearson's r=0.3', 'Cohen's d=0.5', 'OR=1.2').") # Data presented differently [cite: 401, 439, 460]
    statistical_measures: Optional[str] = Field('Percentages, counts, averages (means/medians), rates of change.', description="Other reported statistical measures (e.g., means, SDs, CIs, p-values, regression coefficients).") # [cite: 154, 178, 179, 317, 329, 401, 439, 460]

    # Qualitative Data (Fill if applicable and include_in_extraction is True)
    key_themes: Optional[List[str]] = Field(['Slowdown in office employment growth due to EDP', 'Shift in occupational structure (decline in routine jobs, rise in EDP jobs)', 'Avoidance of layoffs via attrition and transfer', 'Increasing consolidation of functions via EDP ("total system")', 'Impact of input/transmission automation', 'Reduced entry-level job opportunities'], description="Major qualitative themes identified related to labor displacement.")
    text_fragments: Optional[List[str]] = Field(['"Survey results indicate that the growth rate of office staff declines in computerized companies." [cite: 123]', '"EDP reduced employment of punchcard tabulating machine operators, calculators, and routine clerical recordkeeping employees." [cite: 134]', '"Few individuals in the insurance industry were laid off as a direct result of the introduction of EDP." [cite: 444]', '"Jobs had generally been eliminated without recourse to layoffs through the use of attrition and transfer..." [cite: 445]', '"As information became available in complete form in the home office...the limited specialist clerks disappeared." [cite: 305]', '"...insurance offices may not continue to provide a substantial number of openings for young women high school graduates each year." [cite: 140]'], description="Relevant direct quotes or text fragments illustrating displacement impacts.")

    # Historical Context (Only fill if include_in_extraction is True)
    narrative_descriptions: Optional[str] = Field('EDP adoption began mid-1950s, spreading from large to smaller firms. Implementation occurred in phases, leading to consolidation of separate files/departments into integrated systems. This reduced clerical/supervisory roles. Data transmission linked field/home offices, reducing field workload. Optical scanners automated input.', description="Summary of qualitative/narrative accounts of displacement processes and impacts.") # [cite: 48-50, 170-175, 230-246, 255-261, 278-303]
    technological_changes_context: Optional[str] = Field('Shift from electromechanical/punchcard systems to first/second generation computers (vacuum tube, then transistor). Development of auxiliary tech (scanners, data transmission). Trend towards integrated "total systems".', description="Contextual details about the specific technological advancements studied.") # [cite: 79, 80, 81, 104, 192-198, 253, 262, 268, 278, 291]
    economic_conditions: Optional[str] = Field('Period of substantial insurance industry growth (demand driven by rising income, population, ownership). Post-1945 deregulation led to diversification, mergers, new marketing strategies.', description="Broader economic conditions during the study period (e.g., growth, recession, industrialization phase).") #
    institutional_context: Optional[str] = Field('Relaxation of state regulations allowed diversification/mergers. High turnover among female clerical staff enabled attrition-based adjustments. Internal recruitment/retraining common for EDP jobs. Shift work introduced for EDP.', description="Relevant labor policies, regulations, or labor relations context.") # [cite: 67-69, 119, 121, 143, 300, 360, 361, 378, 445]

    # Outcomes and Conclusions (Only fill if include_in_extraction is True)
    main_findings: Optional[str] = Field('EDP significantly slowed office employment growth, especially in firms with longer experience. Led to declines in tabulating, routine clerical, calculating jobs, but growth in EDP roles. Layoffs minimal due to attrition/transfer. Trend towards integrated systems/automation expected to further slow growth (projected 5-10% for 1965-75 vs 32% for 1954-64).', description="Summary of the study's main findings regarding labor displacement.") # [cite: 99-105, 122-125, 134-138, 143-148, 402-406, 436, 444-445, 481, 493, 498-499]
    conclusions: Optional[str] = Field('EDP increases productivity and dampens insurance office employment growth. While past adjustments were smooth due to attrition, future adjustments may be harder. Reduced entry-level clerical opportunities impact new job seekers (esp. young women) and specific communities.', description="The study's overall conclusions on the effects of technology on employment.") # [cite: 139-144, 405-406, 493, 498, 506-516]

    # Quality Assessment (Only fill if include_in_extraction is True)
    methodological_limitations: Optional[str] = Field('Authors note limitations: Mail surveys inadequate for detailed employee adjustment/psychological impact; Difficulty in precise productivity measurement in a service industry[cite: 96, 98, 416, 417]; Hard to isolate EDP effects from simultaneous changes (e.g., mergers)[cite: 396].', description="Limitations of the study methodology as reported by the authors or assessed by the extractor.")
    coherence_assessment: Optional[str] = Field('High. Findings on slowed growth, occupational shifts, and attrition-based adjustment are consistent with survey methods, reported context (industry growth, turnover), and narrative examples.', description="Assessment of how coherent the findings are (e.g., fit between methods and findings).")
    adequacy_assessment: Optional[str] = Field('Moderate to High. Rich survey data on adoption/employment trends, but acknowledged limitations in measuring productivity precisely and capturing individual experiences via mail survey.', description="Assessment of whether the data are rich and sufficient to support the findings.") #
    relevance_assessment_quality: Optional[str] = Field('High. Directly addresses review questions on empirical labor impact of historical technology (EDP) regarding employment trends, occupational structure, and adjustment mechanisms.', description="Assessment of the extent to which the findings are relevant to the review's research questions.")